pipeline {
    agent any

    environment {
        IMAGE_NAME = "ronak2503/myapp"
    }

    stages {

        stage('Clone Source') {
            steps {
                // Clone your actual repository
                git 'https://github.com/Ronak25034/Containerization.git'
            }
        }

        stage('Move to App Directory') {
            steps {
                dir('Lab/Experiment7/my-app') {
                    echo "Inside app directory"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('Lab/Experiment7/my-app') {
                    sh 'docker build -t $IMAGE_NAME:latest .'
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-token', variable: 'DOCKER_TOKEN')]) {
                    sh 'echo $DOCKER_TOKEN | docker login -u ronak2503 --password-stdin'
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh 'docker push $IMAGE_NAME:latest'
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check logs.'
        }
    }
}
